site_name: Tree Machine
nav:
  - Home: index.md
  - User Guide:
    - Base: base.md
    - ClassifierCV: classifier_cv.md
    - RegressionCV: regression_cv.md
  - Appendix:
    - Classification Metrics for ClassifierCV: classification_metrics.md
    - Regression Metrics for RegressionCV: regression_metrics.md
    - ExplainerMixIn: explainer.md
    - OptimizationParams: optimizer_params.md
    - Types: types.md
  - About:
    - License: license.md
  - API:
    - Base: api_base.md
    - ClassifierCV: api_classifier_cv.md
    - RegressionCV: api_regression_cv.md

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_root_members_full_path: false
            show_symbol_type_heading: true
            members_order: alphabetical
            docstring_section_style: table
            show_signature: true
            show_signature_annotations: false
            signature_crossrefs: true
            separate_signature: true
            show_source: true
            line_length: 60
