name: Publish artifacts
on:
  push:
    branches:
      - main
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/bezzanlabs.treemachine/
    permissions:
      id-token: write
    steps:
    - name: git-checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        make install
        make build
        twine check ./dist/*

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ./dist/
