name: Publish artifacts
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        make install

    - name: Builds package
      run: |
        make build

    - name: Checks artifacts and publish them
      run: |
        export TWINE_USERNAME=__token__
        export TWINE_PASSWORD=${{ secrets.PYPI_TOKEN }}
        
        twine check ./dist/*
        twine upload ./dist/* --verbose
